---
title: "Pipeline"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#Allometry Project


> How does plant weight scale with height?

- No relationship
- Linear 
- To the third power
- To the second power


## Load our dataset

```{r}
seeds <- read.csv("https://raw.githubusercontent.com/jmadin/himbr/master/data/seed_root_herbivores.csv", as.is=TRUE)
head (seeds)
summary (seeds)

```


### My first function for SE


```{r}


standard_error <- function (x) {
  se <- sd (x)/sqrt (length (x))
  return (se)
}
```

## Seed height weight after data transformation

```{r}
seeds$Weight_log10 <- log10 (seeds$Weight)
seeds$Height_log10 <- log10(seeds$Height)

```

#Making a model

```{r}
mod <- lm (Weight_log10 ~ Height_log10, dat=seeds)
summary (mod)
mod$coef
write.csv(mod$coef, "output/model_coefs.csv")

```

##Figure plotting

```{r}

h <- sort (seeds$Height_log10)
pred <- predict(mod, list (Height_log10=h), interval="confidence")

pdf ("figs/ figure1.pdf")

plot (Weight_log10 ~ Height_log10, dat=seeds, col="red", xlab="Height, log10", main="Good fig")
lines (h, pred[,1], col="green", lty=2)
polygon (c(h, rev (h)), c(pred [,2], rev (pred [,3])), col=rgb (0,0,1,0.2), border=NA)

dev.off()

```

## Conclusions

Slope of rel b/w height and weight is `r round (mod$coef [2], 2)`.





